# Generated by Django 2.1.1 on 2018-09-18 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxtoken',
            name='wx_credential',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wxapi.WxCredential'),
        ),
    ]
