# Generated by Django 2.1.1 on 2018-09-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapi', '0003_wxsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxcredential',
            name='id',
            field=models.BigAutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wxsession',
            name='id',
            field=models.BigAutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wxtoken',
            name='id',
            field=models.BigAutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
