# Generated by Django 2.1.1 on 2018-09-23 03:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wxapi', '0004_auto_20180922_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxsession',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
